spring.application.name=gerenciador-hotel-spring

springdoc.swagger-ui.path=/swagger-ui.html

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/gerenciador-hotel-spring
spring.datasource.username=postgres
spring.datasource.password=1234567
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.open-in-view=false
spring.jpa.show-sql=false
spring.jpa.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect