springdoc:
  swagger-ui:
    path: /swagger-ui.html

spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:hotel;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: ""
    platform: h2
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect

api:
  security:
    token:
      secret: ${JWT_SECRET:my-secret-key}
      expiration: 2
      issuer: ${JWT_ISSUER:gerenciador-hotel}
